### ISSUE TITLE
Profile support

### ISSUE THREAD

**Issue by Corben78** [Shadnix-was-taken/BeatSaber-SaberTailor#15]
Hey there,

I am playing Beat Saber back and forth with the Vive wands as well as the Valve Index controllers. When switching between them I have to manually adjust the SaberTailor settings. Also when friends are visiting me, they have their own preferences regarding the Saber angle adjustments. 

Would it be feasible to implement a profile support, where several settings can be easily grouped and accessed, and especially switched between just by a click?

**Comment by Shadnix-was-taken** [comment]
Will put this on the long term ToDo list. - I've started changing the UI library for future proofing this mod for the next game update, which should make this task a lot easier.

As a workaround in the mean time, you could keep different copies of the settings file "SaberTailor.json" and swap these around as needed. Might be a bit faster than changing all settings in the menu.

**Comment by Shadnix-was-taken** [comment]
Finally got around to it. The next version will have support for saving the current config to different profiles and for loading those profiles.

**Comment by Shadnix-was-taken** [comment]
Released with 3.0.1.
