### ISSUE TITLE
Misplaced saber handles in 360° pause menu

### ISSUE THREAD

**Issue by Erinaaaaaaa** [Shadnix-was-taken/BeatSaber-SaberTailor#17]
When pausing a 360° level with SaberTailor, if the pause menu is not facing forward, the saber handles will be offset from the menu as much as the menu itself is offset from forward facing ; 

Hopefully this mspaint infographic will help you: 

![image](https://user-images.githubusercontent.com/20820425/70862002-7469b080-1f36-11ea-84ee-7f48fc0ec84e.png)
Green: Forward facing
Blue: To the menu
Orange: where you actually point ingame when physically pointing to the menu

**Comment by Shadnix-was-taken** [comment]
As far as I'm aware right now, this is actually an issue with the base game and can happen regardless of using SaberTailor or not. 

Have you tried running the game without having SaberTailor installed? If yes, was the issue gone for you?

**Comment by Erinaaaaaaa** [comment]
I have indeed ran the game without SaberTailor before reporting the issue
to make sure it was the source of the issue.

I made sure I tested with the same level every time (Glide 360°)

**Comment by Shadnix-was-taken** [comment]
Ok, spent some time troubleshooting this and I was able to reproduce this issue with and without SaberTailor. This is definitely an issue with the base game, but it doesn't seem to occur every time.

The offset is more pronounced with SaberTailor, as your personal settings are then put atop on the wrong base game offset, when this issue occurs. But as of right now, I'm really sure this isn't an issue with the mod.

**Comment by Shadnix-was-taken** [comment]
Will keep this ticket open until the issue got fixed in the base game.

**Comment by Shadnix-was-taken** [comment]
In the meantime, I made a small mod which fixes the issue currently present in the base game. You can get it from here: 
https://github.com/Shadnix-was-taken/BeatSaber-PauseMenuRotationFix/releases/latest

**Comment by Shadnix-was-taken** [comment]
According to Beat Saber change logs, this issue was fixed in the base game in version 1.6.1
