### ISSUE TITLE
World offset not working

### ISSUE THREAD

**Issue by Chr0mia** [Shadnix-was-taken/BeatSaber-SaberTailor#26]
I've noticed that when attempting to change the world offset, the x position works fine but if i try to change the y position it changes the z value by 0.1, however it doesnt go below -0.1 or above 0.1, If I try to change the z value it works but still has the -0.1 - 0.1 range. 

This results in making the y and z world offset settings useless.

**Comment by Shadnix-was-taken** [comment]
Thanks for reporting the issue. I'll try to get to it next week.

**Comment by Shadnix-was-taken** [comment]
Fixed and released in version 3.4.1. Thanks again for reporting the issue.
