### ISSUE TITLE
Not Showing in 1.20

### ISSUE THREAD

**Issue by ThePenguinGamerYT** [Shadnix-was-taken/BeatSaber-SaberTailor#32]
The gui and button to access the main saber choice gui does not show up and there is no way to access it in 1.20 i have tried previous versions and installing the latest version from all sources i can find and none of it is working @Shadnix-was-taken

**Comment by Shadnix-was-taken** [comment]
Hi there and thanks for your bug report.

Just to make sure, based on your error wording of "main saber choice GUI": Might there be a possibility that you are confusing this mod with SaberFactory? SaberTailor is a mod to adjust your grip settings, not to change the appearance of the saber. 

The settings of SaberTailor are currently located in the "Mod options" UI, which is accessable throughout the settings UI. It is not (yet) located on the main menu on the left panel.

If you have the correct mod and it isn't showing up in the mod settings UI, please attach the log file of your last Beat Saber session. That is the "_latest.log" file, which can be found in the "Logs" directory of your Beat Saber installation folder.

**Comment by Shadnix-was-taken** [comment]
Considering there was no follow up here or in the BSMG discord, I'll go ahead and assume this was just the usual mix up between  SaberTailor/SaberFactory and close the ticket.

Feel free to reply if the issue still exists for you.
