### ISSUE TITLE
Ability to apply saber direction/position tweaks to menu laser.

### ISSUE THREAD

**Issue by KingR17** [Shadnix-was-taken/BeatSaber-SaberTailor#7]
I'd like the mod to change the rotation of the laser to match the direction of the saber in game. I switched the rotation of the saber by 180 degrees so I can hold my controllers upside down (much nicer grip I might add). 

However I have to constantly flip my controller around when I leave a song to pick a new one, then rush to flip my controller back around and try to get my grip feeling comfortable again. 

If the selection laser for the menu could be impacted by the rotation values of the saber tweaks, it would make things much nicer.

Thank you for your time!

**Comment by Shadnix-was-taken** [comment]
I think I should be able to implement this. Will probably add an extra setting and leave this disabled in the default state in order to not change the behavior of existing installations.

Will work on this. It will probably completely mess up the originally intended file structure and turn this into spaghetti code territory, but that shouldn't keep it from running. 

Would you mind to beta test a first implementation when I have something finished?

**Comment by KingR17** [comment]
Sure, I'm actually trying to bring a new grip into the meta. A reverse reverse grip. 

https://cdn.discordapp.com/attachments/539558575643820042/581683121221664798/image1.jpg
https://cdn.discordapp.com/attachments/539558575643820042/581683122303926282/image2.jpg

If you want to send it outside of GitHub, you can find me on Discord at KingR17#9632. Whichever's easier.

**Comment by Shadnix-was-taken** [comment]
Ok, here is an updated version for beta testing that should do the job.

[SaberTailor-1.4.0-beta0.zip](https://github.com/Shadnix-was-taken/BeatSaber-SaberTailor/files/3243018/SaberTailor-1.4.0-beta0.zip)

After your first run of Beat Saber with this updated mod, your SaberTailor section in the modprefs.ini file will have an extra option "ModifyMenuHiltGrip". It is set to 0 by default, set it to 1 to enable modification of the menu hilts. 

Small known (and probably annoying) caveat: The modifications won't be active on the health and safety screen. They will be active after loading into the main menu.

Please report any issues you encounter. Or, if it just works as expected, please report that too :).

**Comment by KingR17** [comment]
Sorry for the delay, I’ll give it a try tonight.

**Comment by KingR17** [comment]
From what I can tell, it seems to work fine as intended. I'll keep you posted if I encounter any specific issues, thanks for the addition!

**Comment by Shadnix-was-taken** [comment]
Added in the now released v1.4.0 - menu hilt adjustments now also works immediately at the start in the health and safety warning screen.
